# Generated by Django 4.0.4 on 2022-05-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Homepage',
        ),
    ]
