# Generated by Django 4.0.4 on 2022-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_todo_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='completed',
        ),
        migrations.AddField(
            model_name='homepage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
    ]
