# Generated by Django 4.0.4 on 2022-12-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_status_homepage_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
